Samori79/TFS-Game-Jam-2024

Assets/PlayerTestFolder.meta, Assets/PlayerTestFolder/CharacterBox.prefab, Assets/PlayerTestFolder/CharacterBox.prefab.meta, Assets/PlayerTestFolder/CharacterTestScene.unity, Assets/PlayerTestFolder/CharacterTestScene.unity.meta, Assets/PlayerTestFolder/PlayerMovement.cs, Assets/PlayerTestFolder/PlayerMovement.cs.meta
I have script for a solid cube that has rigidbody2D, and can be controlled via WASD/Arrow Keys to travel along the XY Plane. Note that unity assumes Y is the Up/Down axis so we could make our game along this plane or restructure the code to move the player along XZ but I will have to look into the terminology for this.
=> Basic Playermovement

Assets/Animation.meta, Assets/Animation/JesterAnims.meta, Assets/Animation/JesterAnims/Jester.controller, Assets/Animation/JesterAnims/Jester.controller.meta, Assets/Animation/JesterAnims/JesterDie.anim, Assets/Animation/JesterAnims/JesterDie.anim.meta, Assets/Animation/JesterAnims/JesterFaceBack.anim, Assets/Animation/JesterAnims/JesterFaceBack.anim.meta, Assets/Animation/JesterAnims/JesterFaceFront.anim, Assets/Animation/JesterAnims/JesterFaceFront.anim.meta, Assets/Animation/JesterAnims/JesterFaceLeft.anim, Assets/Animation/JesterAnims/JesterFaceLeft.anim.meta, Assets/Animation/JesterAnims/JesterRunBack.anim, Assets/Animation/JesterAnims/JesterRunBack.anim.meta, Assets/Animation/JesterAnims/JesterRunFront.anim, Assets/Animation/JesterAnims/JesterRunFront.anim.meta, Assets/Animation/JesterAnims/JesterRunLeft.anim, Assets/Animation/JesterAnims/JesterRunLeft.anim.meta, Assets/Animation/JesterAnims/JesterRunRight.anim, Assets/Animation/JesterAnims/JesterRunRight.anim.meta, Assets/Animation/JesterAnims/jesterFaceRight.anim, Assets/Animation/JesterAnims/jesterFaceRight.anim.meta, Assets/PlayerTestFolder/CharacterBox.prefab, Assets/PlayerTestFolder/CharacterTestScene.unity, Assets/PlayerTestFolder/PlayerMovement.cs
Added most of the animations to the player for idle and moving WASD
=> Animations + Player Movement

Assets/Enemies/EnemyAI.cs, Assets/Enemies/EnemyScene.unity, Assets/Prefabs.meta, Assets/Prefabs/Enemy.prefab, Assets/Prefabs/Enemy.prefab.meta
=> Enemy Update

Assets/PlayerTestFolder/CharacterTestScene.unity, Assets/PlayerTestFolder/PlayerMovement.cs
=> Fixed 2drigid to be 3d

Assets/Enemies/EnemyAI.cs, Assets/Enemies/Trap.cs, Assets/Enemies/Trap.cs.meta
=> Basic Trap

Assets/Enemies/EnemyAI.cs, Assets/Enemies/EnemyScene.unity, Assets/Enemies/TestBucket.unity, Assets/Enemies/TestBucket.unity.meta, Assets/Prefabs/Enemy.prefab
=> Shai objects

Assets/Enemies/EnemyAI.cs, Assets/Enemies/Trap.cs, Assets/Enemies/Trigger.cs, Assets/Enemies/Trigger.cs.meta
=> coding fix

Assets/Enemies/EnemyAI.cs
=> coding fix2

Assets/Enemies/EnemyScene.unity, Assets/Enemies/TestBucket.unity, Assets/PlayerTestFolder/PlayerMovement.cs
=> minor player tweaks

Assets/Enemies/Trap.cs, Assets/Enemies/Trigger.cs
=> Lever coding

Assets/Enemies/EnemyScene.unity, Assets/Enemies/Trap.cs, Assets/Enemies/Trigger.cs, Assets/Prefab/lever_low.prefab, ProjectSettings/InputManager.asset
=> Trap and trigger

Assets/Animation/JesterAnims/JesterDie.anim, Assets/Enemies/EnemyScene.unity
=> makes jester die on traps idk

Assets/FrameTest/GameManager.cs, Assets/FrameTest/TestLevel.unity, Assets/FrameTest/testButton.cs, Assets/FrameTest/testButton.cs.meta
we'll see if we even need this
=> messing with menus

Assets/PlayerTestFolder/PlayerMovement.cs
=> player death failscreen

Assets/FinalBuildScenes/MenuScript.cs, Assets/FrameTest/GameManager.cs, Assets/PlayerTestFolder/PlayerMovement.cs
=> player death from enemy

Assets/PlayerTestFolder/PlayerMovement.cs
=> tiny number tweak

Assets/FinalBuildScenes/Level2.unity, Assets/FrameTest/GameManager.cs, Assets/FrameTest/LoadZone3.cs, Assets/FrameTest/LoadZone3.cs.meta, Assets/FrameTest/TestLevel.unity, Assets/Prefab/GameManager.prefab, Assets/Prefab/GameManager.prefab.meta, Assets/Scripts/Door.cs
=> door scene load

Assets/FinalBuildScenes/Level2.unity
=> semi functional level 2

Assets/FinalBuildScenes/Level2.unity
=> Level2 tweaks

Assets/Prefab/CharacterBox.prefab, Assets/Prefab/Enemy.prefab
SHADOWS FOR THE PLAYER AND THE GUARD HAHAHA
=> NOW WITH SHADWOS

Assets/Enemies/EnemyAI.cs, Assets/Enemies/Trap.cs, Assets/PlayerTestFolder/PlayerMovement.cs, Assets/Scripts/Door.cs
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
=> APOCALYPSE NOW
